In [1]:
import pandas as pd
import numpy as np
import matplotlib as plt
from sklearn.datasets import load_breast_cancer
from sklearn.preprocessing import StandardScaler , LabelEncoder
from sklearn.model_selection import train_test_split
import torch

In [2]:
df = pd.read_csv('https://raw.githubusercontent.com/gscdit/Breast-Cancer-Detection/refs/heads/master/data.csv')
df.head()

id diagnosis  radius_mean  texture_mean  perimeter_mean  area_mean  \
0    842302         M        17.99         10.38          122.80     1001.0   
1    842517         M        20.57         17.77          132.90     1326.0   
2  84300903         M        19.69         21.25          130.00     1203.0   
3  84348301         M        11.42         20.38           77.58      386.1   
4  84358402         M        20.29         14.34          135.10     1297.0   

   smoothness_mean  compactness_mean  concavity_mean  concave points_mean  \
0          0.11840           0.27760          0.3001              0.14710   
1          0.08474           0.07864          0.0869              0.07017   
2          0.10960           0.15990          0.1974              0.12790   
3          0.14250           0.28390          0.2414              0.10520   
4          0.10030           0.13280          0.1980              0.10430   

   ...  texture_worst  perimeter_worst  area_worst  smoothness_worst  \
0  ...          17.33           184.60      2019.0            0.1622   
1  ...          23.41           158.80      1956.0            0.1238   
2  ...          25.53           152.50      1709.0            0.1444   
3  ...          26.50            98.87       567.7            0.2098   
4  ...          16.67           152.20      1575.0            0.1374   

   compactness_worst  concavity_worst  concave points_worst  symmetry_worst  \
0             0.6656           0.7119                0.2654          0.4601   
1             0.1866           0.2416                0.1860          0.2750   
2             0.4245           0.4504                0.2430          0.3613   
3             0.8663           0.6869                0.2575          0.6638   
4             0.2050           0.4000                0.1625          0.2364   

   fractal_dimension_worst  Unnamed: 32  
0                  0.11890          NaN  
1                  0.08902          NaN  
2                  0.08758          NaN  
3                  0.17300          NaN  
4                  0.07678          NaN  

[5 rows x 33 columns]

In [3]:
df.shape

(569, 33)

In [4]:
for feature in df:
    print(feature)

id
diagnosis
radius_mean
texture_mean
perimeter_mean
area_mean
smoothness_mean
compactness_mean
concavity_mean
concave points_mean
symmetry_mean
fractal_dimension_mean
radius_se
texture_se
perimeter_se
area_se
smoothness_se
compactness_se
concavity_se
concave points_se
symmetry_se
fractal_dimension_se
radius_worst
texture_worst
perimeter_worst
area_worst
smoothness_worst
compactness_worst
concavity_worst
concave points_worst
symmetry_worst
fractal_dimension_worst
Unnamed: 32


In [5]:
df.drop(columns = ["id","Unnamed: 32"],inplace=True)  

In [6]:
X_train,X_test,y_train,y_test = train_test_split(df.iloc[:,1:],df.iloc[:,0],test_size =0.2)



# df.iloc[:, 1:]
# : → all rows (from top to bottom)
# 1: → starting from column index 1 up to the last column
# ✅ So this gives you all rows and all columns except the first one
# (because the first column is index 0)


# df.iloc[:, 0]
# : → all rows
# 0 → only column at index 0 (the first column)
# ✅ So this gives you all rows from the first column only

In [7]:
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

In [8]:
X_train

array([[-0.36866561,  2.37505976, -0.42042719, ..., -0.73442555,
        -0.83674913, -1.06825939],
       [-1.32634761,  2.01287802, -1.33966754, ..., -1.7152716 ,
        -0.71732162, -0.79074998],
       [ 0.9246486 ,  0.66930057,  0.95489618, ...,  0.5911808 ,
         0.32240024, -0.49607503],
       ...,
       [-0.24276777,  2.05493783, -0.27353184, ..., -0.51404462,
        -0.72083419, -1.09171895],
       [ 0.72721789,  2.05961115,  0.70105435, ...,  0.42514038,
        -1.16868736, -0.30382109],
       [-1.1097461 , -0.40556139, -1.09581293, ..., -0.87374855,
         0.3013248 ,  0.25520303]], shape=(455, 30))

In [9]:
y_train

552    B
557    B
262    M
339    M
268    B
      ..
337    M
134    M
543    B
566    M
222    B
Name: diagnosis, Length: 455, dtype: object

# since the above col is in char form we need to encode it 

In [10]:
encoder = LabelEncoder()
y_train = encoder.fit_transform(y_train)
y_test = encoder.transform(y_test)

In [11]:
y_train 

array([0, 0, 1, 1, 0, 1, 0, 1, 0, 0, 1, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0,
       1, 1, 1, 1, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 1,
       1, 0, 0, 1, 0, 1, 1, 0, 0, 1, 0, 1, 1, 1, 1, 1, 0, 0, 0, 0, 1, 0,
       0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1,
       1, 1, 0, 1, 1, 1, 1, 1, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0,
       1, 0, 1, 1, 0, 1, 0, 1, 1, 1, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 1, 1,
       1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0,
       1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 1, 0, 0,
       0, 1, 1, 0, 1, 0, 0, 1, 1, 1, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0,
       1, 0, 0, 1, 0, 0, 1, 0, 0, 1, 1, 0, 1, 0, 0, 1, 1, 1, 0, 0, 0, 0,
       0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0,

**convert numpy array to tensor of tensorFlow**

In [12]:
X_train_tensor = torch.from_numpy(X_train)
X_test_tensor = torch.from_numpy(X_test)
y_train_tensor = torch.from_numpy(y_train)
y_test_tensor = torch.from_numpy(y_test)

In [13]:
X_train_tensor.shape

torch.Size([455, 30])

In [14]:
X_train_tensor

tensor([[-0.3687,  2.3751, -0.4204,  ..., -0.7344, -0.8367, -1.0683],
        [-1.3263,  2.0129, -1.3397,  ..., -1.7153, -0.7173, -0.7907],
        [ 0.9246,  0.6693,  0.9549,  ...,  0.5912,  0.3224, -0.4961],
        ...,
        [-0.2428,  2.0549, -0.2735,  ..., -0.5140, -0.7208, -1.0917],
        [ 0.7272,  2.0596,  0.7011,  ...,  0.4251, -1.1687, -0.3038],
        [-1.1097, -0.4056, -1.0958,  ..., -0.8737,  0.3013,  0.2552]],
       dtype=torch.float64)

# model Defining

In [15]:
# here we use OOP concept ... we create the class and then write the functions within it 
class MySimpleNN():
    def __init__(self,X):  #here X is the training dataset
        self.weights = torch.rand(X.shape[1], 1, dtype= torch.float64,requires_grad = True)
        self.bias = torch.zeros(1, dtype= torch.float64,requires_grad = True)
        
# explaination:
# X.shape => shape of training dataset i.e> [455,30]
# X.shape[1]=> i.e> 30 
# X.shape[1],1  => this crates a weight matrix of [30 x 1] which helps in calc models weights
# dtype= torch.float64  => stors datatype "float" 
# requires_grad=True → ensures parameters are learnable.


    
    # forward pass
    def forward(self,X):
        z= torch.matmul(X, self.weights) +self.bias   # this is thr formula to find Z = WiXi + W2X2 + b
        y_pred = torch.sigmoid(z)
        return y_pred

    # loss calculation 
    def loss(self,y_pred,y):
        # clamp predictions to avoid log(0)
        epsilon = 1e-7
        y_pred = torch.clamp(y_pred, epsilon, 1-epsilon)

        # calculate loss
        loss = -(y_train_tensor *torch.log(y_pred) + (1- y_train_tensor) * torch.log(1-y_pred)).mean()
        return loss
        
    

# Important Parameter

In [16]:
lr = 0.1 #learning rate 
epochs = 25

# Training Pipeline 

In [17]:
# create model
model = MySimpleNN(X_train_tensor)

# define loops 
for epoch in range(epochs):
    
    # forward pass
    y_pred = model.forward(X_train_tensor)
    # print(y_pred.shape)
    

    # loss calculation
    loss = model.loss(y_pred,y_train_tensor)
    # print(f'epoch :{epoch},loss:{loss.item()}')


    # backward pass
    loss.backward()

    # parameters update
    with torch.no_grad():
        model.weights -= lr * model.weights.grad
        model.bias -= lr * model.bias.grad

    # zero gradients
    model.weights.grad.zero_()
    model.bias.grad.zero_()

    # print loss in each epoch 
    print(f'epoch :{epoch},loss:{loss.item()}')


epoch :0,loss:3.634250539836641
epoch :1,loss:3.509720764946969
epoch :2,loss:3.3793239193280717
epoch :3,loss:3.237596471302975
epoch :4,loss:3.092605418313031
epoch :5,loss:2.9406281161777974
epoch :6,loss:2.7823935261545616
epoch :7,loss:2.6209044085743862
epoch :8,loss:2.454919061277278
epoch :9,loss:2.279602300736212
epoch :10,loss:2.107011864180274
epoch :11,loss:1.9343387751881476
epoch :12,loss:1.7695846894722118
epoch :13,loss:1.6128547456756757
epoch :14,loss:1.4643116494527513
epoch :15,loss:1.3287525896429209
epoch :16,loss:1.2040373437283236
epoch :17,loss:1.0966728722824535
epoch :18,loss:1.0075747153701773
epoch :19,loss:0.9367265692567605
epoch :20,loss:0.8828995174020475
epoch :21,loss:0.8436358710438814
epoch :22,loss:0.8157232985635628
epoch :23,loss:0.7959532078163805
epoch :24,loss:0.7816844102283771


# Model Evaluation 

In [21]:
# model evaluation
with torch.no_grad():
  y_pred = model.forward(X_test_tensor)
  y_pred = (y_pred > 0.9).float()
  accuracy = (y_pred == y_test_tensor).float().mean()
  print(f'Accuracy: {accuracy.item()}')


Accuracy: 0.604032039642334
