In [20]:
import pandas as pd
import numpy as np
import matplotlib as plt
from sklearn.datasets import load_breast_cancer
from sklearn.preprocessing import StandardScaler , LabelEncoder
from sklearn.model_selection import train_test_split
import torch
import torch.nn as nn

In [2]:
df = pd.read_csv('https://raw.githubusercontent.com/gscdit/Breast-Cancer-Detection/refs/heads/master/data.csv')
df.head()

id diagnosis  radius_mean  texture_mean  perimeter_mean  area_mean  \
0    842302         M        17.99         10.38          122.80     1001.0   
1    842517         M        20.57         17.77          132.90     1326.0   
2  84300903         M        19.69         21.25          130.00     1203.0   
3  84348301         M        11.42         20.38           77.58      386.1   
4  84358402         M        20.29         14.34          135.10     1297.0   

   smoothness_mean  compactness_mean  concavity_mean  concave points_mean  \
0          0.11840           0.27760          0.3001              0.14710   
1          0.08474           0.07864          0.0869              0.07017   
2          0.10960           0.15990          0.1974              0.12790   
3          0.14250           0.28390          0.2414              0.10520   
4          0.10030           0.13280          0.1980              0.10430   

   ...  texture_worst  perimeter_worst  area_worst  smoothness_worst  \
0  ...          17.33           184.60      2019.0            0.1622   
1  ...          23.41           158.80      1956.0            0.1238   
2  ...          25.53           152.50      1709.0            0.1444   
3  ...          26.50            98.87       567.7            0.2098   
4  ...          16.67           152.20      1575.0            0.1374   

   compactness_worst  concavity_worst  concave points_worst  symmetry_worst  \
0             0.6656           0.7119                0.2654          0.4601   
1             0.1866           0.2416                0.1860          0.2750   
2             0.4245           0.4504                0.2430          0.3613   
3             0.8663           0.6869                0.2575          0.6638   
4             0.2050           0.4000                0.1625          0.2364   

   fractal_dimension_worst  Unnamed: 32  
0                  0.11890          NaN  
1                  0.08902          NaN  
2                  0.08758          NaN  
3                  0.17300          NaN  
4                  0.07678          NaN  

[5 rows x 33 columns]

In [3]:
df.shape

(569, 33)

In [4]:
for feature in df:
    print(feature)

id
diagnosis
radius_mean
texture_mean
perimeter_mean
area_mean
smoothness_mean
compactness_mean
concavity_mean
concave points_mean
symmetry_mean
fractal_dimension_mean
radius_se
texture_se
perimeter_se
area_se
smoothness_se
compactness_se
concavity_se
concave points_se
symmetry_se
fractal_dimension_se
radius_worst
texture_worst
perimeter_worst
area_worst
smoothness_worst
compactness_worst
concavity_worst
concave points_worst
symmetry_worst
fractal_dimension_worst
Unnamed: 32


In [5]:
df.drop(columns = ["id","Unnamed: 32"],inplace=True)  

In [6]:
X_train,X_test,y_train,y_test = train_test_split(df.iloc[:,1:],df.iloc[:,0],test_size =0.2)



# df.iloc[:, 1:]
# : → all rows (from top to bottom)
# 1: → starting from column index 1 up to the last column
# ✅ So this gives you all rows and all columns except the first one
# (because the first column is index 0)


# df.iloc[:, 0]
# : → all rows
# 0 → only column at index 0 (the first column)
# ✅ So this gives you all rows from the first column only

In [7]:
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

In [8]:
X_train

array([[ 0.10680502, -0.5570005 ,  0.05533528, ..., -0.5567952 ,
        -0.74652755, -0.9892905 ],
       [-0.70787383,  1.18989216, -0.65778755, ...,  0.23722664,
        -0.15579705,  0.91347106],
       [-0.53665319, -0.63295236, -0.54506297, ..., -0.43100956,
        -0.46983482, -0.41801087],
       ...,
       [-0.82662363,  0.12886776, -0.86045194, ..., -1.31211376,
        -0.57338241, -0.41575508],
       [ 0.07642716,  0.01609077,  0.05693421, ..., -0.28980309,
        -0.71936753, -0.50034732],
       [-0.46761261, -0.04605166, -0.43593599, ..., -0.33954284,
        -1.31349303, -0.65543311]], shape=(455, 30))

In [9]:
y_train

486    B
537    B
74     B
239    M
430    M
      ..
7      M
432    M
522    B
448    B
355    B
Name: diagnosis, Length: 455, dtype: object

# since the above col is in char form we need to encode it 

In [10]:
encoder = LabelEncoder()
y_train = encoder.fit_transform(y_train)
y_test = encoder.transform(y_test)

In [11]:
y_train 

array([0, 0, 0, 1, 1, 1, 0, 0, 0, 1, 0, 1, 1, 1, 1, 0, 0, 0, 1, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1,
       1, 0, 1, 0, 0, 1, 1, 0, 0, 1, 0, 1, 0, 0, 1, 0, 1, 1, 0, 1, 0, 0,
       0, 0, 0, 1, 1, 1, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1,
       1, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 1, 1, 1,
       0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 1, 0, 0, 0, 1, 0, 1, 0,
       1, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 1, 1, 0, 0,
       1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 1, 0, 0, 0, 1, 0, 1,
       0, 1, 0, 0, 0, 1, 1, 0, 1, 1, 1, 1, 1, 0, 0, 0, 1, 1, 1, 0, 0, 1,
       1, 0, 0, 0, 1, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 1, 1, 0, 0,
       0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0,
       1, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 1, 1, 0, 0,
       0, 1, 0, 1, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 1, 0,
       0, 1, 0, 0, 1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0,

**convert numpy array to tensor of tensorFlow**

In [12]:
X_train_tensor = torch.from_numpy(X_train)
X_test_tensor = torch.from_numpy(X_test)
y_train_tensor = torch.from_numpy(y_train)
y_test_tensor = torch.from_numpy(y_test)

In [13]:
X_train_tensor.shape

torch.Size([455, 30])

In [14]:
X_train_tensor

tensor([[ 0.1068, -0.5570,  0.0553,  ..., -0.5568, -0.7465, -0.9893],
        [-0.7079,  1.1899, -0.6578,  ...,  0.2372, -0.1558,  0.9135],
        [-0.5367, -0.6330, -0.5451,  ..., -0.4310, -0.4698, -0.4180],
        ...,
        [-0.8266,  0.1289, -0.8605,  ..., -1.3121, -0.5734, -0.4158],
        [ 0.0764,  0.0161,  0.0569,  ..., -0.2898, -0.7194, -0.5003],
        [-0.4676, -0.0461, -0.4359,  ..., -0.3395, -1.3135, -0.6554]],
       dtype=torch.float64)

# model Defining

In [15]:
# here we use OOP concept ... we create the class and then write the functions within it 
class MySimpleNN():
    def __init__(self,X):  #here X is the training dataset
        self.weights = torch.rand(X.shape[1], 1, dtype= torch.float64,requires_grad = True)
        self.bias = torch.zeros(1, dtype= torch.float64,requires_grad = True)
        
# explaination:
# X.shape => shape of training dataset i.e> [455,30]
# X.shape[1]=> i.e> 30 
# X.shape[1],1  => this crates a weight matrix of [30 x 1] which helps in calc models weights
# dtype= torch.float64  => stors datatype "float" 
# requires_grad=True → ensures parameters are learnable.


    
    # forward pass
    def forward(self,X):
        z= torch.matmul(X, self.weights) +self.bias   # this is thr formula to find Z = WiXi + W2X2 + b
        y_pred = torch.sigmoid(z)
        return y_pred

    # loss calculation 
    def loss(self,y_pred,y):
        # clamp predictions to avoid log(0)
        epsilon = 1e-7
        y_pred = torch.clamp(y_pred, epsilon, 1-epsilon)

        # calculate loss
        loss = -(y_train_tensor *torch.log(y_pred) + (1- y_train_tensor) * torch.log(1-y_pred)).mean()
        return loss
        
    

# Important Parameter

In [16]:
lr = 0.1 #learning rate 
epochs = 25

# Training Pipeline 

In [17]:
# create model
model = MySimpleNN(X_train_tensor)

# define loops 
for epoch in range(epochs):
    
    # forward pass
    y_pred = model.forward(X_train_tensor)
    # print(y_pred.shape)
    

    # loss calculation
    loss = model.loss(y_pred,y_train_tensor)
    # print(f'epoch :{epoch},loss:{loss.item()}')


    # backward pass
    loss.backward()

    # parameters update
    with torch.no_grad():
        model.weights -= lr * model.weights.grad
        model.bias -= lr * model.bias.grad

    # zero gradients
    model.weights.grad.zero_()
    model.bias.grad.zero_()

    # print loss in each epoch 
    print(f'epoch :{epoch},loss:{loss.item()}')


epoch :0,loss:3.7436785665178447
epoch :1,loss:3.608632610792192
epoch :2,loss:3.470460773825422
epoch :3,loss:3.330250643708271
epoch :4,loss:3.1845730254493803
epoch :5,loss:3.0346241054336023
epoch :6,loss:2.8787333655771703
epoch :7,loss:2.7194001415233497
epoch :8,loss:2.558717282735535
epoch :9,loss:2.3918854942922394
epoch :10,loss:2.2274522591658688
epoch :11,loss:2.0670372744996968
epoch :12,loss:1.9084496102728696
epoch :13,loss:1.7566699975467512
epoch :14,loss:1.6102291256895616
epoch :15,loss:1.4712192750546091
epoch :16,loss:1.339242802810236
epoch :17,loss:1.2213622005386626
epoch :18,loss:1.119200947263263
epoch :19,loss:1.0356204577035708
epoch :20,loss:0.9698942288006889
epoch :21,loss:0.9198812881361065
epoch :22,loss:0.882502506069966
epoch :23,loss:0.854533193548142
epoch :24,loss:0.8332208869583417


# Model Evaluation 

In [18]:
# model evaluation
with torch.no_grad():
  y_pred = model.forward(X_test_tensor)
  y_pred = (y_pred > 0.9).float()
  accuracy = (y_pred == y_test_tensor).float().mean()
  print(f'Accuracy: {accuracy.item()}')


Accuracy: 0.652046799659729
